name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          ignore: 'dtolnay/rust-toolchain@stable'